### PR TITLE
Add GridWorlds.jl environments

### PR DESCRIPTION
**Pull request by Sid-Bhatia-0**
Allow addition of environments from the `GridWorlds` package.

Added experiment running `BasicDQN` on `EmptyGridWorld` as an example.

image

### CODE REVIEW

**Comment by findmyway** [comment]
Could you tag a new release of GridWorld first? I'm afraid that it won't work for the current version.

**Comment by Sid-Bhatia-0** [comment]
Okay. I want to make sure I understand the reason for this correctly...

`GridWorlds` is added only in `[extras]` and `[targets]` inside `Project.toml`, just like `RLEnvs`. In the case of `RLEnv`, I noticed that only the UUID is mentioned and not the version number. I suppose this means that users will need to add `RLEnvs` on their own (since it is optional) and most of them will do this by `]add ReinforcementLearningEnvironments`. This, by default will add the latest released version of `RLEnvs`.

And when users do try to do the same for GridWorlds by doing `]add GridWorlds`, this which will install `v0.0.1`, the current latest release of `GridWorlds`. And for this version, the code in this PR on `RLZoo` won't work (because `GridWorlds v0.0.1` does not even have the RLBase API). This is what we are trying to prevent, right?

**Comment by findmyway** [comment]
> And when users do try to do the same for GridWorlds by doing ]add GridWorlds, this which will install v0.0.1, the current latest release of GridWorlds. And for this version, the code in this PR on RLZoo won't work (because GridWorlds v0.0.1 does not even have the RLBase API). This is what we are trying to prevent, right?

Exactly! 
(I feel that you're really good at describing the background of the problem we have and offer practical suggestions. This is really something I should learn from 😃 .)

Once https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/issues/116 gets addressed, we can set the compact version of GridWorlds.

**Comment by Sid-Bhatia-0** [comment]
Thank you for your kind words! 😄 

>Once #116 gets addressed, we can set the compact version of GridWorlds.

Okay.

**Comment by findmyway** [comment]
Sorry that I totally forgot this PR.
Could you add a test case so that we can merge this into the master?

**Comment by Sid-Bhatia-0** [comment]
My bad. I forgot too 😅 
I'll close this one and create a new PR hopefully in a few days.

**Comment by findmyway** [comment]
I think this can be closed now?

**Pull request closed without merging**
