### PR TITLE
Add dueling network in Rainbow

### PR DESCRIPTION
**Pull request by pilgrimygy**
I add the dueling network in Rainbow. The result of Cartpole in https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/issues/229.
The result of atari: (Due to equipment and time issues, only part of the data)
avatar

### CODE REVIEW

**Comment by pilgrimygy** [comment]
PPO experiment is broken.

**Comment by pilgrimygy** [comment]
@findmyway The experiment of GridWorld is broken because the package "GridWorld" is changed. I will fix it.

**Comment by findmyway** [comment]
Could you rebase your commit first to avoid bringing in some previously merged ones?

**Comment by findmyway** [comment]
cc @Sid-Bhatia-0  the GridWorld related experiment is now broken.

**Comment by Sid-Bhatia-0** [comment]
Ah.. Yes. Thanks for pointing out.
@pilgrimygy , changing the environment name from `EmptyRoom` to `EmptyRoomDirected` everywhere should fix this.
@findmyway , should I first add a PR to RLZoo to fix this and then this can be rebased?

**Comment by pilgrimygy** [comment]
@Sid-Bhatia-0 I fixed it. If you don't mind, I can push it together with my changes.

**Comment by Sid-Bhatia-0** [comment]
Thanks @pilgrimygy . I was working on it as well.. haha.. I don't mind at all :)

**Comment by findmyway** [comment]
@pilgrimygy The best practice is to fix the tests in another PR. Besides, it seems your commit history is messed up (I can't see the dueling network related PR commits now). You may need to learn how to rebase/squash/merge/forced push

**Comment by pilgrimygy** [comment]
As a newcomer to Git, I'm doing my best to deal with this.

**Pull request closed without merging**
