### PR TITLE
 Adding Actor Critic Network for DDPG Algorithm 

### PR DESCRIPTION
**Pull request by apprenticearnab**
Hi , I am Arnab Kumar Mallick , with some knowledge of reinforcement learning , I have tried to implement the Actor Network for implementing DDPG algorithm from the given [paper reference](https://arxiv.org/pdf/1509.02971.pdf) . I am still working on the critic and DDPG agent development part. Please review it.

### CODE REVIEW

**Comment by findmyway** [comment]
Hi @apprenticearnab ,

Thanks for contributing 😃 . Feel free to ping me when it's ready. My suggestion is to at least add a workable example and then we can discuss how to improve it further to reuse some components in ReinforcementLearningCore.jl

**Comment by findmyway** [comment]
Hi @apprenticearnab ,

Are you still working on this PR? Let me know if you need any help.

**Comment by apprenticearnab** [comment]
No , sir I am unable to work on this PR right now because of writing of Proposal for GSoC , but I promise I will work on it once this process gets over.

**Comment by apprenticearnab** [comment]
I have developed the SAC algorithm baseline using OpenAIGym.jl , shall I make a PR regarding this
 in this repository ? Please reply .

**Comment by findmyway** [comment]
Hi @apprenticearnab ,

That would be great. But I guess you may also need to adapt the code to the APIs here. And adding a test case like those in the `test` folder would be much appreciated.

**Comment by apprenticearnab** [comment]
Please review the code.

**Comment by findmyway** [comment]
Thanks!

I'll review this pr at the weekend.

**Comment by findmyway** [comment]
Closing this PR since a lot of things have changed. Feel free to check out the latest master if you still want to work on this. 🤗

**Comment by apprenticearnab** [comment]
Ok , I will check it out 👍.

**Pull request closed without merging**
